pos_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - shoulder_joint
     - upperArm_joint
     - foreArm_joint
     - wrist1_joint
     - wrist2_joint
     - wrist3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_joint: {trajectory: 0.1, goal: 0.1}
      upperArm_joint: {trajectory: 0.1, goal: 0.1}
      foreArm_joint: {trajectory: 0.1, goal: 0.1}
      wrist1_joint: {trajectory: 0.1, goal: 0.1}
      wrist2_joint: {trajectory: 0.1, goal: 0.1}
      wrist3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains:
    #!!These values are useable, but maybe not optimal
    shoulder_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    upperArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    foreArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
    wrist3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
     
vel_traj_controller:
  type: velocity_controllers/JointTrajectoryController #https://github.com/ros-controls/ros_controllers/blob/melodic-devel/joint_trajectory_controller/ros_control_plugins.xml
  joints:
     - shoulder_joint
     - upperArm_joint
     - foreArm_joint
     - wrist1_joint
     - wrist2_joint
     - wrist3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_joint: {trajectory: 0.1, goal: 0.1}
      upperArm_joint: {trajectory: 0.1, goal: 0.1}
      foreArm_joint: {trajectory: 0.1, goal: 0.1}
      wrist1_joint: {trajectory: 0.1, goal: 0.1}
      wrist2_joint: {trajectory: 0.1, goal: 0.1}
      wrist3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10
  gains:
      #!!These values are useable, but maybe not optimal
      shoulder_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      upperArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      foreArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      wrist3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

      
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - gripper_finger1_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      gripper_finger1_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

aubo_shoulder_joint_vel_controller:
  type: velocity_controllers/JointVelocityController
  joint: shoulder_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    shoulder_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_upper_arm_vel_controller:
  type: velocity_controllers/JointVelocityController
  joint: upperArm_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    upperArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_foreArm_vel_controller:
  type: velocity_controllers/JointVelocityController
  joint: foreArm_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    foreArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_wrist1_vel_controller:
  type: velocity_controllers/JointVelocityController
  joint: wrist1_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    wrist1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_wrist2_vel_controller:
  type: velocity_controllers/JointVelocityController
  joint: wrist2_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    wrist2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_wrist3_vel_controller:
  type: velocity_controllers/JointVelocityController
  joint: wrist3_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    wrist3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

    
aubo_shoulder_joint_pos_controller:
  type: position_controllers/JointPositionController
  joint: shoulder_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    shoulder_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_upper_arm_pos_controller:
  type: position_controllers/JointPositionController
  joint: upperArm_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    upperArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_foreArm_pos_controller:
  type: position_controllers/JointPositionController
  joint: foreArm_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    foreArm_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_wrist1_pos_controller:
  type: position_controllers/JointPositionController
  joint: wrist1_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    wrist1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_wrist2_pos_controller:
  type: position_controllers/JointPositionController
  joint: wrist2_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    wrist2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

aubo_wrist3_pos_controller:
  type: position_controllers/JointPositionController
  joint: wrist3_joint
  pid: {p: 1000.0, i: 0.0, d: 0.7}
  #pid: {p: 50.0, i: 0.1, d: 0.0}
  gains:
    #!!These values are useable, but maybe not optimal
    wrist3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}